### ISSUE TITLE
[Enhancement] Show position in queue in page title

### ISSUE THREAD

**Issue by ryanoconnor7** [CarsonHoffman/office-hours-queue#18]
Right now, the page title reads "EECS 281 Office Hours (36)", 36 being the total number of people in the queue. This is helpful, but while in the queue, I have anxiety of my position moving up, so I either pop the tab out to another window, or constantly keep coming back to the OH tab if I'm working on another tab while waiting. 

It would be nice if the page title read "EECS 281 Office Hours (5 of 36)" or "EECS 281 Office Hours (5/36)" to convey the student's position in the queue (5 in this case). This way, you can quickly gauge if you need to return to the OH page without opening the tab.

**Comment by CarsonHoffman** [comment]
Thank you for the suggestion! I think with so many things going on at the same time that alleviating any potential stressors is a really important goal. I've deployed b29a1f0 which adds a `(#m of n)` to the tab title when you are in the queue, and have moved that to the front of the tab title to help display the information more prominently. Let me know if this is generally what you were thinking, and if you have any other ideas to the end of reducing student stressors (or anything else, really)!

**Comment by ryanoconnor7** [comment]
Yep, this was exactly what I was looking for! Just verified on mobile. Thanks. 

![image](https://user-images.githubusercontent.com/12865081/113184163-daa93e00-9222-11eb-9c7b-44a6bde28a12.jpeg)
