### ISSUE TITLE
[Feature Request] Direct URL to course OH page

### ISSUE THREAD

**Issue by seshrs** [CarsonHoffman/office-hours-queue#2]
It would be nice if a URL like `eecsoh.org/eecs280` loaded the OH page with the correct course pre-selected in the sidebar.

Such a link could be shared with students and added to bookmarks. (I guess the structure of the URL doesn’t matter, fragments or query parameters would work too if they could preselect the correct course.)

---

I originally created jamesjuett/help_queue#63, but it looks like this is the new home for eecsoh.org?

**Comment by CarsonHoffman** [comment]
I've added this functionality in https://github.com/CarsonHoffman/office-hours-queue/commit/ff09da07392f3388b832f87ecc65bf51477ea32f; you can link to a course ID via a fragment, and when you change course pages the fragment is updated for easier copying out of the link.
