### ISSUE TITLE
Feat: Automatic Timezone Convertion

### ISSUE THREAD

**Issue by mertgerdan** [CarsonHoffman/office-hours-queue#30]
As someone who's not in the EST timezone anymore over the summer and had an 8 hour difference a year ago, I emphatize with students who are taking classes remotely from other timezones. What do you think about adding automatic timezone convertion for office hour schedule times?

**Comment by CarsonHoffman** [comment]
Thanks for pointing this out; I hadn't realized that this was an issue. It seems as though unless `local` is explicitly called Moment uses the time zone present in the time it ingests (our server currently sends back RFC3339 strings with an offset of Eastern time), meaning that certain parts of the website (where the date comes directly from the server) were using Eastern time while other parts (where the date is constructed in the browser) were using local time. (This is also why I think that it worked at one point, as the server was sending back timestamps with UTC offsets in the past, which are an equivalently-valid representation but doesn't store that offset information in Moment.) I [just made a pass through the front end to use `local` everywhere it makes sense](https://github.com/CarsonHoffman/office-hours-queue/commit/2014efc4c23de95d7924d31b6eefdeb4d55eee03); it looks like local time is now displayed everywhere. Let me know if you're still having issues with it!

**Comment by mertgerdan** [comment]
Looks like that fixed it, thank you for a quick turnaround!
