### ISSUE TITLE
Priority System 

### ISSUE THREAD

**Issue by NikhilKanamarla** [CarsonHoffman/office-hours-queue#33]
The new priority systems is +n days depending on the last time students joined the queue. However if I pop someone off the queue, and mark them as not helped, they always fall down to +1 instead of +n. Please fix this issue.

**Comment by CarsonHoffman** [comment]
I’m not sure what you’re referring to. No such +n system exists. Are you seeing the effects of randomizing the queue (which randomizes priorities between 0–10)?

**Comment by NikhilKanamarla** [comment]
When I held office hours last weekend, I saw that there were students with +1, +2 etc depending on when they last got helped.

**Comment by CarsonHoffman** [comment]
Again, such a system doesn’t exist. You probably saw a queue that was randomized.

**Comment by CarsonHoffman** [comment]
In fact, you were the one who randomized it!

![image](https://user-images.githubusercontent.com/19721219/192006034-ecbd70e8-1e66-41c4-b4ee-807f7e851871.png)

**Comment by NikhilKanamarla** [comment]
Thanks for clarifying
