### ISSUE TITLE
Use of Notification API for watching Queue on both ends

### ISSUE THREAD

**Issue by Zalanshah64** [CarsonHoffman/office-hours-queue#36]
[Notification](https://developer.mozilla.org/en-US/docs/Web/API/notification) is an API that can give users a notification, per the user's permission. This would prove itself useful on both ends -- IA and student.

For students in long queues, they can opt in to get a notification when they're next on the queue or got popped off the queue.

For IAs in dry queues, they can opt in to get a notification when a student joins the queue.

In either case, this can prove itself very useful, as it would give real time information to people about the queue without needing to actively look at it. This would especially be useful for virtual queues.

**Comment by CarsonHoffman** [comment]
We already do this in both situations, no? Notifications are sent [when you're popped](https://github.com/CarsonHoffman/office-hours-queue/blob/d2dde2568e3816f94dc07c9c1f99f8abc376c960/frontend/src/types/OrderedQueue.ts#L157-L160) and when [a student shows up on an empty queue](https://github.com/CarsonHoffman/office-hours-queue/blob/d2dde2568e3816f94dc07c9c1f99f8abc376c960/frontend/src/types/OrderedQueue.ts#L100-L103).

**Comment by Zalanshah64** [comment]
That's strange. For some reason, I've never gotten notifications for students showing into empty queues, and my notification settings are on for the site.

Perhaps this may be a bug?

**Comment by CarsonHoffman** [comment]
If you have a reproduction case from a fresh browser, please let me know. It's hard to narrow it down otherwise. Notifications work in all of Safari, Firefox and Chrome on my end.
