### ISSUE TITLE
Feature request: students cannot sign up again until end of cooldown period

### ISSUE THREAD

**Issue by mariamhmahmoud** [CarsonHoffman/office-hours-queue#37]
Lots of students sign up immediately after an instructor helps them. It would be nice if students weren't allowed to sign up again until after a course designated cooldown period. For example, if EECS 485 didn't want students to be able to sign up again until 15 minutes after they were last helped, they should not be able to.

Another alternative: simply post on student cards when they were last helped/signed up so instructors can manually manage this.

**Comment by jkloosterman** [comment]
+1

**Comment by CarsonHoffman** [comment]
I just implemented this in https://github.com/CarsonHoffman/office-hours-queue/commit/7f80cb27f738338988bdfd0309c0004ca7aa9186. I'll deploy it later tonight. As a reminder while you're testing: admins can always sign up, so this will only take effect if you're not an admin (and only if you didn't help yourself, as that doesn't count).

**Comment by CarsonHoffman** [comment]
This has been deployed, so I'm closing this issue. Let me know if you have any other concerns.
