### ISSUE TITLE
[Enhancement] Sort Classes by name

### ISSUE THREAD

**Issue by Zalanshah64** [CarsonHoffman/office-hours-queue#42]
Sorting classes by name, rather than by order they were added to the website, would be more intuitive and help students more easily find the classes they need.

Of course, this shouldn't affect starred classes, as they should be in the order they were starred (allowing students to completely customize that which they care about).

**Comment by CarsonHoffman** [comment]
I've had this thought in the back of my mind for a while; thanks for bringing it up. I think this is the right way to go about things. I've implemented this in [97119a6](https://github.com/CarsonHoffman/office-hours-queue/commit/97119a62c4510d56ba197a9476bca6fb572d2e93) and deployed it!

I didn't implement the starred sorting as you mentioned; things didn't work like this previously, and the way I'm storing favorite courses is unordered, meaning some additional adaptation would be needed for that. Given that someone is likely to only have a few courses starred, I don't think this is the biggest omission, and I didn't want it to prevent progress here.
