### ISSUE TITLE
[Enhancement] On mobile: URLs in announcement text do not wrap

### ISSUE THREAD

**Issue by seshrs** [CarsonHoffman/office-hours-queue#7]
Here's what I see when I open the EECS 485 Queue page on a mobile device:

![image](https://user-images.githubusercontent.com/12139762/104672090-16654a80-56ad-11eb-9b27-9985af72368d.png)

It would be nice to add CSS property `word-break: break-word;` to any text that could contain long URLs to ensure that they wrap correctly.

**Comment by CarsonHoffman** [comment]
Good catch; I thought I had caught all of these (like in queue entries), but I missed this one. Should be fixed by 14f7f44; this commit is deployed and working on my end (iPhone XS).
