### ISSUE TITLE
Relative timestamp in queue incorrectly shows "an hour ago" after 45 min

### ISSUE THREAD

**Issue by ryanoconnor7** [CarsonHoffman/office-hours-queue#9]
It looks like the relative timestamp in each row of the queue is showing "an hour ago" when (`now - timeJoined > 45 min`). I think this is misleading and it should show the relative minutes until they reach >= 60.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/12865081/107375617-f01da980-6ab6-11eb-9915-c82d7ef033c8.png">
<img width="95" alt="image" src="https://user-images.githubusercontent.com/12865081/107375639-f6138a80-6ab6-11eb-90ab-67ff71c98b3c.png">

**Comment by CarsonHoffman** [comment]
This is a product of [moment.js' default humanize thresholds](https://momentjscom.readthedocs.io/en/latest/moment/07-customization/13-relative-time-threshold/); I do agree that this might be confusing when jumping between two students on the queue (from 44 minutes to an hour), so I think that changing them (at least for minutes->hour and hours->days) is a good idea.

**Comment by CarsonHoffman** [comment]
This is implemented in 1562ef4 and currently live on the site (it might take a few refreshes to bust your cache); let me know if this works better!

**Comment by ryanoconnor7** [comment]
Verified! I think that's clearer. Moment.js is fun for sure 😅
